---
name: "Container build and test"
on:
  push:
  pull_request:
  workflow_call:
  paths:
    - container-source/**
permissions: read-all

jobs:
  podman-build:
    name: Utility Container Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Utility Container Build
        run: make build

      - name: Run Container tests
        run: make test
